import '../../styles/globals.scss'
import React from "react";
import { i18n } from '@/i18n-config'
import {getDictionary} from "@/get-message";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
    return i18n.locales.map((locale) => ({ lang: locale }))
}


interface RootLayoutInterface {
    children : React.ReactNode;
    params : {lang :string};
}

export default async function RootLayout({children , params :{lang}}: RootLayoutInterface) {
    const dictionary = await getDictionary(lang)
  return (
    <html lang={lang}>
      <body>
      <header>
          {dictionary['header'].title}
      </header>

      <main>
          {children}
      </main>

      <footer>
          {dictionary['footer'].title}
      </footer>

      </body>
    </html>
  )
}
